import type { IngredientSlot } from "@/lib/claude";

export const INGREDIENT_SEEDS: Record<IngredientSlot, string[]> = {
  setting: [
    "An underwater library carved from coral",
    "A floating market on the back of a giant turtle",
    "A bakery hidden inside a hollow oak tree",
    "A cloud city stitched together by rope bridges",
    "A frozen palace where every room is a different season",
    "A jungle temple guarded by friendly stone tigers",
    "A train that rides on rainbows between planets",
    "A village built into the cracks of a sleeping dragon",
    "A glass observatory on the edge of a glowing crater",
    "A music box kingdom that resets every time it spins",
  ],
  character: [
    "A forgetful octopus librarian with eight reading glasses",
    "A tiny dragon who breathes bubbles instead of fire",
    "A robot gardener powered by sunbeams",
    "A kid wizard whose hat tells jokes",
    "A fox detective with a notebook full of star maps",
    "A shy ghost who delivers letters between worlds",
    "An astronaut chef searching for the perfect snack",
    "A clumsy knight who befriends every creature she meets",
    "A musical kid whose flute can talk to weather",
    "A brave puppy with a glowing collar of stars",
  ],
  goal: [
    "Find the stolen Book of Tides before the moon rises",
    "Wake up the sleeping mountain by singing its true name",
    "Plant a seed that grows a bridge between two lands",
    "Return a lost shadow to its very confused owner",
    "Collect every color before the sunset paints them away",
    "Throw the worlds biggest party for the lonely north wind",
    "Carry a tiny flame across a kingdom of soft snow",
    "Solve the riddle hidden inside a whispering door",
    "Catch the runaway stars before they tumble out of the sky",
    "Teach a sad volcano how to laugh again",
  ],
  twist: [
    "The thief is your own shadow",
    "Every promise you make becomes a real bird",
    "Time runs backward whenever you laugh",
    "Your best friend is secretly the moon in disguise",
    "The map only shows the truth when you whisper to it",
    "Magic only works while you are holding hands with a stranger",
    "The villain is just a friend who lost their memory",
    "Each step you take plants a flower that remembers you",
    "You can hear what animals dream about at night",
    "The world ends if anyone says your real name out loud",
  ],
};
