// B-011 themes catalog. 6 themes × 15 sub-scenes = 90 background nodes with
// a directed graph (connects_to) for geographic adjacency. Backs the new
// theme-driven landing flow:
//
// - Kid picks a theme on the landing page.
// - Kid picks (or types) an entry sub-scene from that theme's grid.
// - The /api/generate route validates the picks against this catalog and
//   passes the picked theme's full sub-scene list to lib/claude.ts as
//   context.
// - Claude builds a story tree where scene 1 == entry, scenes 2-4 follow
//   library connects_to edges from the previous scene, scenes 5+ may use
//   any sub-scene in the same theme, and ending scenes use sub-scenes
//   flagged can_be_ending.
// - The renderer resolves scene.background_id via SUB_SCENES_BY_ID[id]
//   .file_path. Old worlds (theme = null in DB) keep falling through to the
//   B-010 matcher path.
//
// String ids + runtime validation, no literal unions. validateThemeCatalog
// (in lib/catalog-validator.ts) runs at module load and throws on init if
// any cross-reference is broken.

import { validateThemeCatalog } from "@/lib/catalog-validator";

export type SubScene = {
  id: string;
  theme: string;
  label: string;
  description: string;
  file_path: string;
  connects_to: string[];
  can_be_entry: boolean;
  can_be_ending: boolean;
  // B-013 pilot: optional entry video that plays once on first scene entry
  // per (world_id, scene_id), then crossfades to file_path. Drawbridge only.
  entry_video_path?: string;
  // B-012 gates: pickup ids the player must hold before the gating choice
  // unlocks. Validated against lib/pickups-catalog at module load. Claude
  // reads this list and emits matching `requires` arrays on the choice
  // leading INTO this sub-scene. Empty/undefined means no gate.
  required_pickups?: string[];
  // B-021 demo polish: when true, the sub-scene tile renders locked in the
  // landing form's "where do you start" picker. Used to hide every castle
  // entry except the dragon-egg quest tile for the demo.
  locked?: boolean;
};

export type Theme = {
  id: string;
  label: string;
  description: string;
  thumbnail_path: string;
  sub_scenes: SubScene[];
  // B-021 demo polish: when true, the theme tile renders grayscale with a
  // 🔒 overlay and is not selectable. Castle is the only unlocked theme for
  // the hackathon demo; other themes still appear in the catalog for the
  // future build-out.
  locked?: boolean;
};

const castleSubScenes: SubScene[] = [
  // B-021 demo polish: the only castle entry point exposed in the demo
  // landing form. Routes the kid into the Hunt the Dragon's Egg adventure.
  // Every other castle sub-scene below is locked for the hackathon demo.
  {
    id: "castle_dragon_egg_quest",
    theme: "castle",
    label: "Collect the Dragon's Egg",
    description: "the dragon's nest cavern with a single glowing egg",
    file_path: "/backgrounds/castle/dragon_egg_quest.webp",
    connects_to: ["castle_drawbridge"],
    can_be_entry: true,
    can_be_ending: false,
  },
  {
    id: "castle_drawbridge",
    theme: "castle",
    label: "Drawbridge",
    description: "wooden bridge over a moat, chains taut, gulls overhead",
    file_path: "/backgrounds/castle/drawbridge.webp",
    connects_to: ["castle_outer_gate", "castle_secret_passage"],
    can_be_entry: true,
    can_be_ending: false,
    // B-013 pilot. Generated via Replicate kwaivgi/kling-v1.6-pro on the
    // drawbridge.webp starting frame. Plays once per (world_id, scene_id) in
    // sessionStorage; tap-to-skip; 200ms crossfade to file_path on end.
    entry_video_path: "/backgrounds/castle/drawbridge_entry.mp4",
    locked: true,
  },
  {
    id: "castle_outer_gate",
    theme: "castle",
    label: "Outer Gate",
    description: "tall arched gate with iron portcullis, flagstones underfoot",
    file_path: "/backgrounds/castle/outer_gate.svg",
    connects_to: ["castle_drawbridge", "castle_courtyard", "castle_royal_garden"],
    can_be_entry: true,
    can_be_ending: false,
    locked: true,
  },
  {
    id: "castle_courtyard",
    theme: "castle",
    label: "Courtyard",
    description: "open stone courtyard with fountain and banners",
    file_path: "/backgrounds/castle/courtyard.svg",
    connects_to: [
      "castle_outer_gate",
      "castle_great_hall",
      "castle_kitchen",
      "castle_royal_garden",
    ],
    can_be_entry: false,
    can_be_ending: false,
    locked: true,
  },
  {
    id: "castle_great_hall",
    theme: "castle",
    label: "Great Hall",
    description: "vaulted hall with long banquet table and crackling hearth",
    file_path: "/backgrounds/castle/great_hall.svg",
    connects_to: [
      "castle_courtyard",
      "castle_throne_room",
      "castle_library",
      "castle_tower_stairs",
      "castle_kitchen",
    ],
    can_be_entry: false,
    can_be_ending: false,
    locked: true,
  },
  {
    id: "castle_throne_room",
    theme: "castle",
    label: "Throne Room",
    description: "tall stained glass behind a velvet throne, royal silence",
    file_path: "/backgrounds/castle/throne_room.svg",
    connects_to: ["castle_great_hall", "castle_royal_chambers"],
    can_be_entry: false,
    can_be_ending: true,
    locked: true,
  },
  {
    id: "castle_dungeon",
    theme: "castle",
    label: "Dungeon",
    description: "stone cells lit by sputtering torches, distant drips",
    file_path: "/backgrounds/castle/dungeon.svg",
    connects_to: ["castle_secret_passage", "castle_ancient_crypt"],
    can_be_entry: false,
    can_be_ending: true,
    required_pickups: ["torch"],
    locked: true,
  },
  {
    id: "castle_kitchen",
    theme: "castle",
    label: "Kitchen",
    description: "warm kitchen with bread, copper pots and a roaring fire",
    file_path: "/backgrounds/castle/kitchen.svg",
    connects_to: ["castle_courtyard", "castle_great_hall", "castle_secret_passage"],
    can_be_entry: false,
    can_be_ending: false,
    locked: true,
  },
  {
    id: "castle_library",
    theme: "castle",
    label: "Library",
    description: "tall shelves of leather books, dust motes in candle light",
    file_path: "/backgrounds/castle/library.svg",
    connects_to: ["castle_great_hall", "castle_royal_chambers", "castle_secret_passage"],
    can_be_entry: false,
    can_be_ending: false,
    required_pickups: ["rusty_key"],
    locked: true,
  },
  {
    id: "castle_royal_chambers",
    theme: "castle",
    label: "Royal Chambers",
    description: "grand bedroom with a four-poster bed and a balcony",
    file_path: "/backgrounds/castle/royal_chambers.svg",
    connects_to: [
      "castle_throne_room",
      "castle_library",
      "castle_tower_stairs",
      "castle_tower_top",
    ],
    can_be_entry: false,
    can_be_ending: false,
    locked: true,
  },
  {
    id: "castle_tower_stairs",
    theme: "castle",
    label: "Tower Stairs",
    description: "spiral stone stairs winding up a narrow tower shaft",
    file_path: "/backgrounds/castle/tower_stairs.svg",
    connects_to: ["castle_great_hall", "castle_royal_chambers", "castle_tower_top"],
    can_be_entry: false,
    can_be_ending: false,
    required_pickups: ["climbing_rope"],
    locked: true,
  },
  {
    id: "castle_tower_top",
    theme: "castle",
    label: "Tower Top",
    description: "open battlement above the clouds with sweeping views",
    file_path: "/backgrounds/castle/tower_top.svg",
    connects_to: ["castle_tower_stairs", "castle_royal_chambers"],
    can_be_entry: false,
    can_be_ending: true,
    locked: true,
  },
  {
    id: "castle_royal_garden",
    theme: "castle",
    label: "Royal Garden",
    description: "hedge maze, rose beds, and a stone bench in the sun",
    file_path: "/backgrounds/castle/royal_garden.svg",
    connects_to: ["castle_outer_gate", "castle_courtyard", "castle_dragons_lair"],
    can_be_entry: false,
    can_be_ending: false,
    locked: true,
  },
  {
    id: "castle_secret_passage",
    theme: "castle",
    label: "Secret Passage",
    description: "narrow hidden corridor lit by glowing moss and old paint",
    file_path: "/backgrounds/castle/secret_passage.svg",
    connects_to: [
      "castle_drawbridge",
      "castle_kitchen",
      "castle_library",
      "castle_dungeon",
      "castle_ancient_crypt",
    ],
    can_be_entry: false,
    can_be_ending: false,
    locked: true,
  },
  {
    id: "castle_dragons_lair",
    theme: "castle",
    label: "Dragon's Lair",
    description: "huge cavern of gold piles and warm scaly shadows",
    file_path: "/backgrounds/castle/dragons_lair.svg",
    connects_to: ["castle_royal_garden", "castle_ancient_crypt"],
    can_be_entry: false,
    can_be_ending: true,
    required_pickups: ["dragons_lullaby"],
    locked: true,
  },
  {
    id: "castle_ancient_crypt",
    theme: "castle",
    label: "Ancient Crypt",
    description: "forgotten crypt of stone tombs, candles still flickering",
    file_path: "/backgrounds/castle/ancient_crypt.svg",
    connects_to: ["castle_dungeon", "castle_secret_passage", "castle_dragons_lair"],
    can_be_entry: false,
    can_be_ending: true,
    required_pickups: ["ancient_tome"],
    locked: true,
  },
];

const forestSubScenes: SubScene[] = [
  {
    id: "forest_edge",
    theme: "forest",
    label: "Forest Edge",
    description: "where the trees begin, sun slipping through new leaves",
    file_path: "/backgrounds/forest/edge.svg",
    connects_to: ["forest_mossy_path", "forest_old_oak_clearing"],
    can_be_entry: true,
    can_be_ending: false,
  },
  {
    id: "forest_mossy_path",
    theme: "forest",
    label: "Mossy Path",
    description: "soft moss-covered trail twisting between tall trunks",
    file_path: "/backgrounds/forest/mossy_path.svg",
    connects_to: ["forest_edge", "forest_old_oak_clearing", "forest_babbling_brook"],
    can_be_entry: true,
    can_be_ending: false,
  },
  {
    id: "forest_old_oak_clearing",
    theme: "forest",
    label: "Old Oak Clearing",
    description: "ancient oak in a sunny ring of grass and acorns",
    file_path: "/backgrounds/forest/old_oak_clearing.svg",
    connects_to: [
      "forest_edge",
      "forest_mossy_path",
      "forest_hidden_pond",
      "forest_mushroom_grove",
      "forest_hollow_tree",
    ],
    can_be_entry: false,
    can_be_ending: false,
  },
  {
    id: "forest_hidden_pond",
    theme: "forest",
    label: "Hidden Pond",
    description: "a quiet pond ringed by ferns, with darting silver fish",
    file_path: "/backgrounds/forest/hidden_pond.svg",
    connects_to: [
      "forest_old_oak_clearing",
      "forest_babbling_brook",
      "forest_foggy_marsh",
      "forest_fairy_glade",
    ],
    can_be_entry: false,
    can_be_ending: false,
  },
  {
    id: "forest_witchs_cottage",
    theme: "forest",
    label: "Witch's Cottage",
    description: "a crooked little cottage with a smoking chimney",
    file_path: "/backgrounds/forest/witchs_cottage.svg",
    connects_to: ["forest_mushroom_grove", "forest_stone_circle", "forest_foggy_marsh"],
    can_be_entry: false,
    can_be_ending: true,
  },
  {
    id: "forest_stone_circle",
    theme: "forest",
    label: "Stone Circle",
    description: "ring of mossy standing stones humming with old magic",
    file_path: "/backgrounds/forest/stone_circle.svg",
    connects_to: ["forest_babbling_brook", "forest_witchs_cottage", "forest_ancient_tree"],
    can_be_entry: false,
    can_be_ending: false,
  },
  {
    id: "forest_babbling_brook",
    theme: "forest",
    label: "Babbling Brook",
    description: "shallow stream over smooth stones, dragonflies above",
    file_path: "/backgrounds/forest/babbling_brook.svg",
    connects_to: [
      "forest_mossy_path",
      "forest_hidden_pond",
      "forest_foggy_marsh",
      "forest_stone_circle",
    ],
    can_be_entry: false,
    can_be_ending: false,
  },
  {
    id: "forest_mushroom_grove",
    theme: "forest",
    label: "Mushroom Grove",
    description: "rings of giant red and blue mushrooms glowing softly",
    file_path: "/backgrounds/forest/mushroom_grove.svg",
    connects_to: [
      "forest_old_oak_clearing",
      "forest_fairy_glade",
      "forest_witchs_cottage",
    ],
    can_be_entry: false,
    can_be_ending: false,
  },
  {
    id: "forest_hollow_tree",
    theme: "forest",
    label: "Hollow Tree",
    description: "a giant hollow trunk with a tiny door at its base",
    file_path: "/backgrounds/forest/hollow_tree.svg",
    connects_to: [
      "forest_old_oak_clearing",
      "forest_treetop_bridge",
      "forest_bears_den",
    ],
    can_be_entry: false,
    can_be_ending: false,
  },
  {
    id: "forest_treetop_bridge",
    theme: "forest",
    label: "Treetop Bridge",
    description: "rope walkway high in the canopy, leaves whispering",
    file_path: "/backgrounds/forest/treetop_bridge.svg",
    connects_to: ["forest_hollow_tree", "forest_ancient_tree", "forest_forest_heart"],
    can_be_entry: false,
    can_be_ending: false,
  },
  {
    id: "forest_fairy_glade",
    theme: "forest",
    label: "Fairy Glade",
    description: "a sunlit clearing of tiny doors and floating lights",
    file_path: "/backgrounds/forest/fairy_glade.svg",
    connects_to: [
      "forest_hidden_pond",
      "forest_mushroom_grove",
      "forest_forest_heart",
    ],
    can_be_entry: false,
    can_be_ending: true,
  },
  {
    id: "forest_bears_den",
    theme: "forest",
    label: "Bear's Den",
    description: "warm cave with a sleeping shape and big paw prints",
    file_path: "/backgrounds/forest/bears_den.svg",
    connects_to: ["forest_hollow_tree", "forest_foggy_marsh"],
    can_be_entry: false,
    can_be_ending: true,
  },
  {
    id: "forest_foggy_marsh",
    theme: "forest",
    label: "Foggy Marsh",
    description: "lily pads, mist, and the call of unseen frogs",
    file_path: "/backgrounds/forest/foggy_marsh.svg",
    connects_to: [
      "forest_hidden_pond",
      "forest_babbling_brook",
      "forest_witchs_cottage",
      "forest_bears_den",
    ],
    can_be_entry: false,
    can_be_ending: false,
  },
  {
    id: "forest_ancient_tree",
    theme: "forest",
    label: "Ancient Tree",
    description: "a tree as wide as a house with carved roots and runes",
    file_path: "/backgrounds/forest/ancient_tree.svg",
    connects_to: [
      "forest_treetop_bridge",
      "forest_stone_circle",
      "forest_forest_heart",
    ],
    can_be_entry: false,
    can_be_ending: true,
  },
  {
    id: "forest_forest_heart",
    theme: "forest",
    label: "Forest Heart",
    description: "deepest clearing of green light where the woods listen",
    file_path: "/backgrounds/forest/forest_heart.svg",
    connects_to: [
      "forest_treetop_bridge",
      "forest_ancient_tree",
      "forest_fairy_glade",
    ],
    can_be_entry: false,
    can_be_ending: true,
  },
];

const candySubScenes: SubScene[] = [
  {
    id: "candy_gumdrop_gates",
    theme: "candy_land",
    label: "Gumdrop Gates",
    description: "tall sticky gates of red and green gumdrops",
    file_path: "/backgrounds/candy_land/gumdrop_gates.svg",
    connects_to: ["candy_lollipop_forest", "candy_marshmallow_meadow"],
    can_be_entry: true,
    can_be_ending: false,
  },
  {
    id: "candy_lollipop_forest",
    theme: "candy_land",
    label: "Lollipop Forest",
    description: "swirling lollipop trees in pink, orange, and lime",
    file_path: "/backgrounds/candy_land/lollipop_forest.svg",
    connects_to: [
      "candy_gumdrop_gates",
      "candy_marshmallow_meadow",
      "candy_chocolate_river",
    ],
    can_be_entry: true,
    can_be_ending: false,
  },
  {
    id: "candy_marshmallow_meadow",
    theme: "candy_land",
    label: "Marshmallow Meadow",
    description: "soft white field of squishy marshmallow tufts",
    file_path: "/backgrounds/candy_land/marshmallow_meadow.svg",
    connects_to: [
      "candy_gumdrop_gates",
      "candy_lollipop_forest",
      "candy_gingerbread_village",
      "candy_sprinkle_meadow",
    ],
    can_be_entry: false,
    can_be_ending: false,
  },
  {
    id: "candy_chocolate_river",
    theme: "candy_land",
    label: "Chocolate River",
    description: "thick brown river bubbling between cocoa banks",
    file_path: "/backgrounds/candy_land/chocolate_river.svg",
    connects_to: [
      "candy_lollipop_forest",
      "candy_gingerbread_village",
      "candy_bubblegum_bridge",
      "candy_caramel_cave",
    ],
    can_be_entry: false,
    can_be_ending: false,
  },
  {
    id: "candy_gingerbread_village",
    theme: "candy_land",
    label: "Gingerbread Village",
    description: "tiny gingerbread houses with icing roofs and candy windows",
    file_path: "/backgrounds/candy_land/gingerbread_village.svg",
    connects_to: [
      "candy_marshmallow_meadow",
      "candy_chocolate_river",
      "candy_bubblegum_bridge",
      "candy_donut_hole",
      "candy_royal_sugar_castle",
    ],
    can_be_entry: false,
    can_be_ending: false,
  },
  {
    id: "candy_cotton_candy_clouds",
    theme: "candy_land",
    label: "Cotton Candy Clouds",
    description: "fluffy pink clouds floating above the candy land",
    file_path: "/backgrounds/candy_land/cotton_candy_clouds.svg",
    connects_to: [
      "candy_ice_cream_mountain",
      "candy_cake_tower",
      "candy_sprinkle_meadow",
      "candy_bubblegum_bridge",
    ],
    can_be_entry: false,
    can_be_ending: false,
  },
  {
    id: "candy_ice_cream_mountain",
    theme: "candy_land",
    label: "Ice Cream Mountain",
    description: "a snowy peak of vanilla, mint, and strawberry scoops",
    file_path: "/backgrounds/candy_land/ice_cream_mountain.svg",
    connects_to: ["candy_cotton_candy_clouds", "candy_cake_tower"],
    can_be_entry: false,
    can_be_ending: true,
  },
  {
    id: "candy_caramel_cave",
    theme: "candy_land",
    label: "Caramel Cave",
    description: "warm golden cave dripping with sticky caramel",
    file_path: "/backgrounds/candy_land/caramel_cave.svg",
    connects_to: ["candy_chocolate_river", "candy_donut_hole", "candy_sour_patch_swamp"],
    can_be_entry: false,
    can_be_ending: false,
  },
  {
    id: "candy_bubblegum_bridge",
    theme: "candy_land",
    label: "Bubblegum Bridge",
    description: "stretchy pink bridge that bounces with every step",
    file_path: "/backgrounds/candy_land/bubblegum_bridge.svg",
    connects_to: [
      "candy_chocolate_river",
      "candy_gingerbread_village",
      "candy_cotton_candy_clouds",
    ],
    can_be_entry: false,
    can_be_ending: false,
  },
  {
    id: "candy_donut_hole",
    theme: "candy_land",
    label: "Donut Hole",
    description: "a sticky tunnel through a giant glazed donut",
    file_path: "/backgrounds/candy_land/donut_hole.svg",
    connects_to: [
      "candy_gingerbread_village",
      "candy_caramel_cave",
      "candy_sour_patch_swamp",
    ],
    can_be_entry: false,
    can_be_ending: false,
  },
  {
    id: "candy_royal_sugar_castle",
    theme: "candy_land",
    label: "Royal Sugar Castle",
    description: "a glittering crystal sugar castle with rock candy spires",
    file_path: "/backgrounds/candy_land/royal_sugar_castle.svg",
    connects_to: [
      "candy_gingerbread_village",
      "candy_cake_tower",
      "candy_sugar_plum_garden",
    ],
    can_be_entry: false,
    can_be_ending: true,
  },
  {
    id: "candy_sour_patch_swamp",
    theme: "candy_land",
    label: "Sour Patch Swamp",
    description: "fizzy sour pools dotted with pucker-faced candies",
    file_path: "/backgrounds/candy_land/sour_patch_swamp.svg",
    connects_to: [
      "candy_caramel_cave",
      "candy_donut_hole",
      "candy_sugar_plum_garden",
    ],
    can_be_entry: false,
    can_be_ending: false,
  },
  {
    id: "candy_cake_tower",
    theme: "candy_land",
    label: "Cake Tower",
    description: "a tall tiered cake with frosting balconies and candles",
    file_path: "/backgrounds/candy_land/cake_tower.svg",
    connects_to: [
      "candy_cotton_candy_clouds",
      "candy_ice_cream_mountain",
      "candy_royal_sugar_castle",
    ],
    can_be_entry: false,
    can_be_ending: true,
  },
  {
    id: "candy_sprinkle_meadow",
    theme: "candy_land",
    label: "Sprinkle Meadow",
    description: "rainbow sprinkles scattered across a soft frosting field",
    file_path: "/backgrounds/candy_land/sprinkle_meadow.svg",
    connects_to: [
      "candy_marshmallow_meadow",
      "candy_cotton_candy_clouds",
      "candy_sugar_plum_garden",
    ],
    can_be_entry: false,
    can_be_ending: false,
  },
  {
    id: "candy_sugar_plum_garden",
    theme: "candy_land",
    label: "Sugar Plum Garden",
    description: "purple sugar plum trees humming a sweet lullaby",
    file_path: "/backgrounds/candy_land/sugar_plum_garden.svg",
    connects_to: [
      "candy_royal_sugar_castle",
      "candy_sour_patch_swamp",
      "candy_sprinkle_meadow",
    ],
    can_be_entry: false,
    can_be_ending: true,
  },
];

const citySubScenes: SubScene[] = [
  {
    id: "city_subway_entrance",
    theme: "city",
    label: "Subway Entrance",
    description: "stairs descending into a humming subway with green tiles",
    file_path: "/backgrounds/city/subway_entrance.svg",
    connects_to: ["city_bus_stop", "city_alley", "city_underground_tunnel"],
    can_be_entry: true,
    can_be_ending: false,
  },
  {
    id: "city_bus_stop",
    theme: "city",
    label: "Bus Stop",
    description: "yellow bench under a glass shelter on a busy corner",
    file_path: "/backgrounds/city/bus_stop.svg",
    connects_to: ["city_subway_entrance", "city_park", "city_diner"],
    can_be_entry: true,
    can_be_ending: false,
  },
  {
    id: "city_park",
    theme: "city",
    label: "Park",
    description: "trees and benches around a winding gravel path",
    file_path: "/backgrounds/city/park.svg",
    connects_to: [
      "city_bus_stop",
      "city_public_library",
      "city_river_bridge",
      "city_school",
    ],
    can_be_entry: false,
    can_be_ending: false,
  },
  {
    id: "city_public_library",
    theme: "city",
    label: "Public Library",
    description: "tall stone library with a marble lion at the steps",
    file_path: "/backgrounds/city/public_library.svg",
    connects_to: ["city_park", "city_museum", "city_school"],
    can_be_entry: false,
    can_be_ending: false,
  },
  {
    id: "city_school",
    theme: "city",
    label: "School",
    description: "brick school with a basketball hoop in the schoolyard",
    file_path: "/backgrounds/city/school.svg",
    connects_to: [
      "city_park",
      "city_public_library",
      "city_comic_shop",
      "city_market_square",
    ],
    can_be_entry: false,
    can_be_ending: false,
  },
  {
    id: "city_skyscraper_lobby",
    theme: "city",
    label: "Skyscraper Lobby",
    description: "tall lobby with shiny floors and a gold elevator bank",
    file_path: "/backgrounds/city/skyscraper_lobby.svg",
    connects_to: [
      "city_rooftop",
      "city_alley",
      "city_market_square",
      "city_river_bridge",
    ],
    can_be_entry: false,
    can_be_ending: false,
  },
  {
    id: "city_rooftop",
    theme: "city",
    label: "Rooftop",
    description: "windy roof with antennas and a view of the whole skyline",
    file_path: "/backgrounds/city/rooftop.svg",
    connects_to: ["city_skyscraper_lobby", "city_alley"],
    can_be_entry: false,
    can_be_ending: true,
  },
  {
    id: "city_diner",
    theme: "city",
    label: "Diner",
    description: "cozy diner with red booths and a humming neon sign",
    file_path: "/backgrounds/city/diner.svg",
    connects_to: ["city_bus_stop", "city_comic_shop", "city_market_square"],
    can_be_entry: false,
    can_be_ending: false,
  },
  {
    id: "city_comic_shop",
    theme: "city",
    label: "Comic Shop",
    description: "tiny shop walled with bright comic covers and toy boxes",
    file_path: "/backgrounds/city/comic_shop.svg",
    connects_to: ["city_school", "city_diner", "city_alley", "city_movie_theater"],
    can_be_entry: false,
    can_be_ending: false,
  },
  {
    id: "city_river_bridge",
    theme: "city",
    label: "River Bridge",
    description: "long iron bridge over slow river water and ferries",
    file_path: "/backgrounds/city/river_bridge.svg",
    connects_to: ["city_park", "city_museum", "city_skyscraper_lobby"],
    can_be_entry: false,
    can_be_ending: false,
  },
  {
    id: "city_museum",
    theme: "city",
    label: "Museum",
    description: "marble halls of dinosaur bones and quiet glass cases",
    file_path: "/backgrounds/city/museum.svg",
    connects_to: [
      "city_public_library",
      "city_river_bridge",
      "city_market_square",
      "city_underground_tunnel",
    ],
    can_be_entry: false,
    can_be_ending: true,
  },
  {
    id: "city_alley",
    theme: "city",
    label: "Alley",
    description: "narrow brick alley with fire escapes and chalk drawings",
    file_path: "/backgrounds/city/alley.svg",
    connects_to: [
      "city_subway_entrance",
      "city_skyscraper_lobby",
      "city_comic_shop",
      "city_underground_tunnel",
      "city_movie_theater",
      "city_rooftop",
    ],
    can_be_entry: false,
    can_be_ending: false,
  },
  {
    id: "city_market_square",
    theme: "city",
    label: "Market Square",
    description: "bustling open square of fruit stalls and street art",
    file_path: "/backgrounds/city/market_square.svg",
    connects_to: [
      "city_school",
      "city_skyscraper_lobby",
      "city_diner",
      "city_museum",
      "city_movie_theater",
    ],
    can_be_entry: false,
    can_be_ending: false,
  },
  {
    id: "city_movie_theater",
    theme: "city",
    label: "Movie Theater",
    description: "old movie palace with a glowing marquee at dusk",
    file_path: "/backgrounds/city/movie_theater.svg",
    connects_to: ["city_comic_shop", "city_alley", "city_market_square"],
    can_be_entry: false,
    can_be_ending: true,
  },
  {
    id: "city_underground_tunnel",
    theme: "city",
    label: "Underground Tunnel",
    description: "long subway tunnel with rumbling tracks and old graffiti",
    file_path: "/backgrounds/city/underground_tunnel.svg",
    connects_to: ["city_subway_entrance", "city_alley", "city_museum"],
    can_be_entry: false,
    can_be_ending: true,
  },
];

const spaceSubScenes: SubScene[] = [
  {
    id: "space_spaceship_bridge",
    theme: "space",
    label: "Spaceship Bridge",
    description: "command bridge of a small starship with a starfield ahead",
    file_path: "/backgrounds/space/spaceship_bridge.svg",
    connects_to: ["space_launch_pad", "space_asteroid_field", "space_space_station"],
    can_be_entry: true,
    can_be_ending: false,
  },
  {
    id: "space_launch_pad",
    theme: "space",
    label: "Launch Pad",
    description: "open launch pad under a desert sky, rocket steaming",
    file_path: "/backgrounds/space/launch_pad.svg",
    connects_to: ["space_spaceship_bridge", "space_moon_base", "space_robot_factory"],
    can_be_entry: true,
    can_be_ending: false,
  },
  {
    id: "space_asteroid_field",
    theme: "space",
    label: "Asteroid Field",
    description: "drifting rocks tumbling silently against a blue nebula",
    file_path: "/backgrounds/space/asteroid_field.svg",
    connects_to: [
      "space_spaceship_bridge",
      "space_moon_base",
      "space_comet_tail",
      "space_nebula_cloud",
    ],
    can_be_entry: false,
    can_be_ending: false,
  },
  {
    id: "space_moon_base",
    theme: "space",
    label: "Moon Base",
    description: "glassy domes and rover tracks across pale lunar dust",
    file_path: "/backgrounds/space/moon_base.svg",
    connects_to: [
      "space_launch_pad",
      "space_asteroid_field",
      "space_crystal_cave_mars",
      "space_robot_factory",
      "space_space_station",
    ],
    can_be_entry: false,
    can_be_ending: false,
  },
  {
    id: "space_alien_planet_surface",
    theme: "space",
    label: "Alien Planet Surface",
    description: "purple grass under twin suns and a glassy sky",
    file_path: "/backgrounds/space/alien_planet_surface.svg",
    connects_to: [
      "space_crystal_cave_mars",
      "space_nebula_cloud",
      "space_wormhole",
    ],
    can_be_entry: false,
    can_be_ending: false,
  },
  {
    id: "space_black_hole_edge",
    theme: "space",
    label: "Black Hole Edge",
    description: "a slow swirl at the rim of a tilting dark disk",
    file_path: "/backgrounds/space/black_hole_edge.svg",
    connects_to: ["space_wormhole", "space_galaxy_edge"],
    can_be_entry: false,
    can_be_ending: true,
  },
  {
    id: "space_space_station",
    theme: "space",
    label: "Space Station",
    description: "ring station turning slowly with bright porthole lights",
    file_path: "/backgrounds/space/space_station.svg",
    connects_to: [
      "space_spaceship_bridge",
      "space_moon_base",
      "space_robot_factory",
      "space_comet_tail",
    ],
    can_be_entry: false,
    can_be_ending: false,
  },
  {
    id: "space_crystal_cave_mars",
    theme: "space",
    label: "Crystal Cave on Mars",
    description: "rusty cave full of glowing red and blue crystals",
    file_path: "/backgrounds/space/crystal_cave_mars.svg",
    connects_to: [
      "space_moon_base",
      "space_alien_planet_surface",
      "space_robot_factory",
    ],
    can_be_entry: false,
    can_be_ending: false,
  },
  {
    id: "space_nebula_cloud",
    theme: "space",
    label: "Nebula Cloud",
    description: "swirling pink and gold gas with new stars sparking inside",
    file_path: "/backgrounds/space/nebula_cloud.svg",
    connects_to: [
      "space_asteroid_field",
      "space_alien_planet_surface",
      "space_comet_tail",
      "space_star_heart",
    ],
    can_be_entry: false,
    can_be_ending: false,
  },
  {
    id: "space_comet_tail",
    theme: "space",
    label: "Comet Tail",
    description: "icy comet streaking through the dark with a long bright tail",
    file_path: "/backgrounds/space/comet_tail.svg",
    connects_to: [
      "space_asteroid_field",
      "space_space_station",
      "space_nebula_cloud",
      "space_suns_outer_ring",
    ],
    can_be_entry: false,
    can_be_ending: false,
  },
  {
    id: "space_star_heart",
    theme: "space",
    label: "Star Heart",
    description: "a calm bright core inside a young star, humming with light",
    file_path: "/backgrounds/space/star_heart.svg",
    connects_to: [
      "space_nebula_cloud",
      "space_suns_outer_ring",
      "space_galaxy_edge",
    ],
    can_be_entry: false,
    can_be_ending: true,
  },
  {
    id: "space_wormhole",
    theme: "space",
    label: "Wormhole",
    description: "swirling tunnel of stretched starlight bending forward",
    file_path: "/backgrounds/space/wormhole.svg",
    connects_to: [
      "space_alien_planet_surface",
      "space_black_hole_edge",
      "space_galaxy_edge",
    ],
    can_be_entry: false,
    can_be_ending: false,
  },
  {
    id: "space_robot_factory",
    theme: "space",
    label: "Robot Factory",
    description: "huge hangar of folding arms building bright little robots",
    file_path: "/backgrounds/space/robot_factory.svg",
    connects_to: [
      "space_launch_pad",
      "space_moon_base",
      "space_space_station",
      "space_crystal_cave_mars",
    ],
    can_be_entry: false,
    can_be_ending: false,
  },
  {
    id: "space_galaxy_edge",
    theme: "space",
    label: "Galaxy Edge",
    description: "the rim of a spiral galaxy, all dark beyond",
    file_path: "/backgrounds/space/galaxy_edge.svg",
    connects_to: [
      "space_black_hole_edge",
      "space_star_heart",
      "space_wormhole",
      "space_suns_outer_ring",
    ],
    can_be_entry: false,
    can_be_ending: true,
  },
  {
    id: "space_suns_outer_ring",
    theme: "space",
    label: "Sun's Outer Ring",
    description: "blazing prominences arcing along the surface of a young sun",
    file_path: "/backgrounds/space/suns_outer_ring.svg",
    connects_to: [
      "space_comet_tail",
      "space_star_heart",
      "space_galaxy_edge",
    ],
    can_be_entry: false,
    can_be_ending: true,
  },
];

const underwaterSubScenes: SubScene[] = [
  {
    id: "underwater_sandy_shore",
    theme: "underwater",
    label: "Sandy Shore",
    description: "warm shallows lapping a quiet white beach",
    file_path: "/backgrounds/underwater/sandy_shore.svg",
    connects_to: ["underwater_coral_reef_edge", "underwater_kelp_forest"],
    can_be_entry: true,
    can_be_ending: false,
  },
  {
    id: "underwater_coral_reef_edge",
    theme: "underwater",
    label: "Coral Reef Edge",
    description: "edge of a bright coral reef with darting tropical fish",
    file_path: "/backgrounds/underwater/coral_reef_edge.svg",
    connects_to: [
      "underwater_sandy_shore",
      "underwater_kelp_forest",
      "underwater_reef_cliffs",
      "underwater_octopus_garden",
    ],
    can_be_entry: true,
    can_be_ending: false,
  },
  {
    id: "underwater_kelp_forest",
    theme: "underwater",
    label: "Kelp Forest",
    description: "tall green kelp swaying in shafts of slow sunlight",
    file_path: "/backgrounds/underwater/kelp_forest.svg",
    connects_to: [
      "underwater_sandy_shore",
      "underwater_coral_reef_edge",
      "underwater_sunken_ship",
      "underwater_octopus_garden",
      "underwater_pirate_wreck",
    ],
    can_be_entry: false,
    can_be_ending: false,
  },
  {
    id: "underwater_sunken_ship",
    theme: "underwater",
    label: "Sunken Ship",
    description: "an old wooden ship leaning on the seabed, lit by jellyfish",
    file_path: "/backgrounds/underwater/sunken_ship.svg",
    connects_to: [
      "underwater_kelp_forest",
      "underwater_treasure_cave",
      "underwater_pirate_wreck",
    ],
    can_be_entry: false,
    can_be_ending: false,
  },
  {
    id: "underwater_mermaid_palace",
    theme: "underwater",
    label: "Mermaid Palace",
    description: "tall pearl spires and shell windows lit by glowfish",
    file_path: "/backgrounds/underwater/mermaid_palace.svg",
    connects_to: [
      "underwater_pearl_cave",
      "underwater_octopus_garden",
      "underwater_lost_atlantis",
    ],
    can_be_entry: false,
    can_be_ending: true,
  },
  {
    id: "underwater_deep_trench",
    theme: "underwater",
    label: "Deep Trench",
    description: "narrow blue trench dropping into the cold dark deep",
    file_path: "/backgrounds/underwater/deep_trench.svg",
    connects_to: [
      "underwater_abyss",
      "underwater_whale_bones",
      "underwater_underwater_volcano",
      "underwater_pirate_wreck",
    ],
    can_be_entry: false,
    can_be_ending: true,
  },
  {
    id: "underwater_treasure_cave",
    theme: "underwater",
    label: "Treasure Cave",
    description: "small cave glittering with old coins and sea glass",
    file_path: "/backgrounds/underwater/treasure_cave.svg",
    connects_to: [
      "underwater_sunken_ship",
      "underwater_pearl_cave",
      "underwater_pirate_wreck",
    ],
    can_be_entry: false,
    can_be_ending: false,
  },
  {
    id: "underwater_octopus_garden",
    theme: "underwater",
    label: "Octopus Garden",
    description: "a quiet garden of bright shells tended by a kind octopus",
    file_path: "/backgrounds/underwater/octopus_garden.svg",
    connects_to: [
      "underwater_coral_reef_edge",
      "underwater_kelp_forest",
      "underwater_mermaid_palace",
      "underwater_reef_cliffs",
    ],
    can_be_entry: false,
    can_be_ending: false,
  },
  {
    id: "underwater_whale_bones",
    theme: "underwater",
    label: "Whale Bones",
    description: "huge pale ribs arching over the seafloor like a tunnel",
    file_path: "/backgrounds/underwater/whale_bones.svg",
    connects_to: [
      "underwater_deep_trench",
      "underwater_underwater_volcano",
      "underwater_abyss",
      "underwater_reef_cliffs",
    ],
    can_be_entry: false,
    can_be_ending: false,
  },
  {
    id: "underwater_underwater_volcano",
    theme: "underwater",
    label: "Underwater Volcano",
    description: "a steaming volcanic vent in a ring of black stone",
    file_path: "/backgrounds/underwater/underwater_volcano.svg",
    connects_to: [
      "underwater_deep_trench",
      "underwater_whale_bones",
      "underwater_abyss",
      "underwater_lost_atlantis",
    ],
    can_be_entry: false,
    can_be_ending: false,
  },
  {
    id: "underwater_pearl_cave",
    theme: "underwater",
    label: "Pearl Cave",
    description: "a hidden cave of giant glowing pearls in a soft pink hue",
    file_path: "/backgrounds/underwater/pearl_cave.svg",
    connects_to: ["underwater_mermaid_palace", "underwater_treasure_cave"],
    can_be_entry: false,
    can_be_ending: true,
  },
  {
    id: "underwater_reef_cliffs",
    theme: "underwater",
    label: "Reef Cliffs",
    description: "tall coral cliffs that drop away into deeper blue",
    file_path: "/backgrounds/underwater/reef_cliffs.svg",
    connects_to: [
      "underwater_coral_reef_edge",
      "underwater_octopus_garden",
      "underwater_whale_bones",
    ],
    can_be_entry: false,
    can_be_ending: false,
  },
  {
    id: "underwater_pirate_wreck",
    theme: "underwater",
    label: "Pirate Wreck",
    description: "a broken pirate ship hanging on a ledge above the trench",
    file_path: "/backgrounds/underwater/pirate_wreck.svg",
    connects_to: [
      "underwater_kelp_forest",
      "underwater_sunken_ship",
      "underwater_treasure_cave",
      "underwater_deep_trench",
    ],
    can_be_entry: false,
    can_be_ending: false,
  },
  {
    id: "underwater_lost_atlantis",
    theme: "underwater",
    label: "Lost Atlantis",
    description: "tall white columns of a forgotten city, lit by sunbeams",
    file_path: "/backgrounds/underwater/lost_atlantis.svg",
    connects_to: [
      "underwater_mermaid_palace",
      "underwater_underwater_volcano",
      "underwater_abyss",
    ],
    can_be_entry: false,
    can_be_ending: true,
  },
  {
    id: "underwater_abyss",
    theme: "underwater",
    label: "Abyss",
    description: "true deep dark with strange glowing shapes far below",
    file_path: "/backgrounds/underwater/abyss.svg",
    connects_to: [
      "underwater_deep_trench",
      "underwater_whale_bones",
      "underwater_underwater_volcano",
      "underwater_lost_atlantis",
    ],
    can_be_entry: false,
    can_be_ending: true,
  },
];

export const THEMES: Theme[] = [
  {
    id: "castle",
    label: "Castle and Dragons",
    description: "stone halls, secret passages, and the dragon below",
    thumbnail_path: "/themes/castle.webp",
    sub_scenes: castleSubScenes,
  },
  {
    id: "forest",
    label: "Forest",
    description: "old oaks, hidden ponds, and quiet magic in the moss",
    thumbnail_path: "/themes/forest.svg",
    sub_scenes: forestSubScenes,
    locked: true,
  },
  {
    id: "candy_land",
    label: "Candy Land",
    description: "lollipop trees, chocolate rivers, and a sugar castle",
    thumbnail_path: "/themes/candy_land.svg",
    sub_scenes: candySubScenes,
    locked: true,
  },
  {
    id: "city",
    label: "City",
    description: "subways, rooftops, comic shops, and bright sidewalks",
    thumbnail_path: "/themes/city.svg",
    sub_scenes: citySubScenes,
    locked: true,
  },
  {
    id: "space",
    label: "Space",
    description: "rockets, moon bases, nebulae, and the wide dark beyond",
    thumbnail_path: "/themes/space.svg",
    sub_scenes: spaceSubScenes,
    locked: true,
  },
  {
    id: "underwater",
    label: "Underwater",
    description: "coral cliffs, kelp forests, sunken ships, and the deep",
    thumbnail_path: "/themes/underwater.svg",
    sub_scenes: underwaterSubScenes,
    locked: true,
  },
];

validateThemeCatalog(THEMES);

export const THEMES_BY_ID: Record<string, Theme> = Object.fromEntries(
  THEMES.map((t) => [t.id, t])
);

export const SUB_SCENES_BY_ID: Record<string, SubScene> = Object.fromEntries(
  THEMES.flatMap((t) => t.sub_scenes.map((s) => [s.id, s] as const))
);

export const ALL_THEME_IDS: Set<string> = new Set(THEMES.map((t) => t.id));

export function getTheme(themeId: string): Theme | null {
  return THEMES_BY_ID[themeId] ?? null;
}

export function getSubScene(subSceneId: string): SubScene | null {
  return SUB_SCENES_BY_ID[subSceneId] ?? null;
}

export function isValidThemeId(id: string): boolean {
  return ALL_THEME_IDS.has(id);
}

export function isValidSubSceneId(id: string): boolean {
  return id in SUB_SCENES_BY_ID;
}

export function subScenesForTheme(themeId: string): SubScene[] {
  return THEMES_BY_ID[themeId]?.sub_scenes ?? [];
}
