#!/usr/bin/env tsx
// Scan public/assets/{category}/ and write lib/asset-files.generated.ts so
// the manifest knows which assets have real .png versus placeholder .svg.
// Run after generate-assets.ts (or after manually dropping curated PNGs).

import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { ASSET_LIBRARY } from "../lib/asset-library";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");

main();

async function main() {
  const map: Record<string, "svg" | "png"> = {};
  for (const a of ASSET_LIBRARY) {
    const pngPath = path.join(ROOT, "public/assets", a.category, `${a.id}.png`);
    try {
      await fs.stat(pngPath);
      map[a.id] = "png";
    } catch {
      map[a.id] = "svg";
    }
  }
  const counts = countBy(map);
  const out = `// Generated by scripts/sync-asset-files.ts. Do not edit by hand.
// Maps asset id to the file extension actually present on disk.
// Keep in sync after generating real PNGs.

export const ASSET_FILE_EXTENSIONS: Record<string, "svg" | "png"> = ${JSON.stringify(map, null, 2)};
`;
  await fs.writeFile(path.join(ROOT, "lib/asset-files.generated.ts"), out, "utf-8");
  console.log(`Wrote asset-files.generated.ts. PNG: ${counts.png}, SVG: ${counts.svg}`);
}

function countBy(m: Record<string, "svg" | "png">) {
  let png = 0;
  let svg = 0;
  for (const v of Object.values(m)) {
    if (v === "png") png++;
    else svg++;
  }
  return { png, svg };
}
